### ISSUE TITLE
Develop an onBoarding screen

### ISSUE THREAD

**Issue by XxThunderBlastxX** [XxThunderBlastxX/chamting-app#11]

**Comment by sagnik-sanyal** [comment]
Hey can you describe the issue , do we have to design the page in figma or code the ui ?

**Comment by XxThunderBlastxX** [comment]
@sagnik-sanyal You have to code the UI. It will be a basic screen, with two buttons. One as SignUp and another as SignIn button. You can still apply some styling by taking some reference from other screens.

**Comment by Uttkarsh-raj** [comment]
Hey, I am interested in solving this issue . Can you assign me this and share a reference if you have one.

**Comment by XxThunderBlastxX** [comment]
@Uttkarsh-raj go ahead
