### ISSUE TITLE
Design an logo for the app 

### ISSUE THREAD

**Issue by XxThunderBlastxX** [XxThunderBlastxX/chamting-app#12]

**Comment by XxThunderBlastxX** [comment]
Sure go ahead

**Comment by Akansha3001** [comment]
Thanks for assigning the issue. May I know what kind of logo are you looking for? Do you have any special vision regarding it?

**Comment by XxThunderBlastxX** [comment]
I currently dont have anything in my mind as of now. Whatever comes in you mind with the app theme. You can make a logo with that and post in discord channel. And we all can discuss on that. What do u think about this ?

**Comment by Akansha3001** [comment]
Yaa, sure we can do that!
Will be sharing the logo on the discord channel

**Comment by Gun2902** [comment]
can u assign me trhis issue

**Comment by XxThunderBlastxX** [comment]
@Akansha3001 Its a medium issue, for which I can only provide you 2-3 days. It has been 4 days since I assigned you this issue. 
Please make an PR by tonight or I have to assign to someone else.

**Comment by Akansha3001** [comment]
> @Akansha3001 Its a medium issue, for which I can only provide you 2-3 days. It has been 4 days since I assigned you this issue. Please make an PR by tonight or I have to assign to someone else.

Hi! I'm so sorry for the inconvenience caused. I have made the pull request. I've designed 6 logos, you can choose the most appropriate one. Also, shall I share those designs on Discord as well for others to review?

**Comment by XxThunderBlastxX** [comment]
Yeah sure @Akansha3001

**Comment by Akansha3001** [comment]
@XxThunderBlastxX Shared the designs on discord!

**Comment by sagnik-sanyal** [comment]
I am ready to work on this issue. I can go ahead on designing the logo

**Comment by XxThunderBlastxX** [comment]
@sagnik-sanyal @Gun2902 Its respective PR is already made. You still look into other issue.
