### ISSUE TITLE
Make proper project structure 

### ISSUE THREAD

**Issue by XxThunderBlastxX** [XxThunderBlastxX/chamting-app#3]

**Comment by sagnik-sanyal** [comment]
hey i am ready to work on this issue under JWOC , before proceeding can i know why did you prefer bloc of riverpod

**Comment by sagnik-sanyal** [comment]
Hey there @XxThunderBlastxX can i start on this ?

**Comment by XxThunderBlastxX** [comment]
@sagnik-sanyal yes u can go ahead.
Bloc is more flexible and scalable in terms of management. You can even do with riverpod. I think that would make the overall project much simpler.

**Comment by sagnik-sanyal** [comment]
Hey there @XxThunderBlastxX i have generated the PR for this issue, please have a look at it and do lemme know if there are any issues

**Comment by sagnik-sanyal** [comment]
Hey @XxThunderBlastxX i have created the PR please merge it if there are no issues
