### ISSUE TITLE
Want to add some documentation

### ISSUE THREAD

**Issue by Sowham-3098** [XxThunderBlastxX/chamting-app#31]
Want to add CODE_OF_CONDUCT.md and also update your readme.md

**Comment by XxThunderBlastxX** [comment]
@Sowham-3098  go ahead

**Comment by Sowham-3098** [comment]
I want to work on it under JWOC

**Comment by XxThunderBlastxX** [comment]
@Sowham-3098 I have already assigned to u , u can start work on it.
