### ISSUE TITLE
Make login screen UI for the app

### ISSUE THREAD

**Issue by XxThunderBlastxX** [XxThunderBlastxX/chamting-app#5]

**Comment by Uttkarsh-raj** [comment]
hii @XxThunderBlastxX  I am interested in contributing to this project. I would like to ask if you already have a design that you want to implement and can you please assign this issue to me.

**Comment by XxThunderBlastxX** [comment]
Sure, I will assign you. I will share one ref img on discord channel . U can refer to it.

**Comment by Uttkarsh-raj** [comment]
@XxThunderBlastxX ,where can i get the discord link.

**Comment by XxThunderBlastxX** [comment]
You can go to the discord server and in chamting-app u can find all the information . Also future information.

**Comment by azutsavv** [comment]
please assign this issue to me as its been more than 3 days and there is no pr generated .

**Comment by Gun2902** [comment]
can u assign me this issue

**Comment by XxThunderBlastxX** [comment]
@Gun2902 it is already assigned to someone else, So I can't assign u right now . U can have a look at other issues. Or if you find any new issue you can tell me, I will make it for you .
