### ISSUE TITLE
Add an Windows title bar 

### ISSUE THREAD

**Issue by XxThunderBlastxX** [XxThunderBlastxX/chamting-app#9]

**Comment by SoumyadeepOSD** [comment]
@XxThunderBlastxX  If you give the more information about this issue I can try to contribute to it

**Comment by XxThunderBlastxX** [comment]
@SoumyadeepOSD Its the long top bar you can see for any application. It consist of minimize, maximize , close button on right hand side.

You can use bitsdogo_windows package for this as well. 

While doing this I would suggest you to make it as a common reusable widget.

**Comment by XxThunderBlastxX** [comment]
Go for it

**Comment by sagnik-sanyal** [comment]
@XxThunderBlastxX i want to work on this issue after my latest PR #21 is merged. Can i take up this issue after it is merged ?

**Comment by Uttkarsh-raj** [comment]
I would like to work on this issue... Can you please assign this to me..
